### ISSUE TITLE
linux Fortran and cmake

### ISSUE THREAD

**Issue by loriab** [AnacondaRecipes/aggregate#66]
Sorry, found another missing file from conda compilers. This one isn't bothering me, so consider it purely FYI.

In package `gfortran_linux-64`, there looks to be neither `omp_lib.mod` nor `omp_lib.h`, thus cmake's newest OpenMP detection, which looks for either for Fortran, fails. The recipe below should trigger the fail. Curiously, I haven't had problems actually building threaded Fortran programs with the conda compilers (at least compile-time), and I've seen these headers in older conda gfortran, hence my hope that it's a simple file inclusion fix.

`fortomp/build.sh` 
```
${BUILD_PREFIX}/bin/cmake \
    -H${SRC_DIR} \
    -Bbuild \
    -DCMAKE_INSTALL_PREFIX=${PREFIX} \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_Fortran_COMPILER=${GFORTRAN} \
    -DCMAKE_Fortran_FLAGS="${FFLAGS}"
```

`fortomp/src/CMakeLists.txt`
```
cmake_minimum_required(VERSION 3.3 FATAL_ERROR)
project(fortomp
        LANGUAGES Fortran)

find_package(OpenMP REQUIRED)
```

`fortomp/meta.yaml`
```
package:
    name: fortomp
    version: 0.1

source:
    path: ./src

build:
    number: 0  # [linux]

requirements:
    build:
        - cmake 3.11*
        - {{ compiler('fortran') }}  # OpenMP not found, as no omp_lib header or module
                                     # https://github.com/Kitware/CMake/blob/master/Modules/FindOpenMP.cmake#L55-L60
```
