### ISSUE TITLE
Please provide instruction on how to compile compatible packages

### ISSUE THREAD

**Issue by 183amir** [AnacondaRecipes/aggregate#7]
Please provide instruction on how to compile compatible packages with packages from here.
The old repository: https://github.com/ContinuumIO/anaconda-recipes had a README which contained this instructions. Would it be possible to provide the same thing here?

**Comment by msarahan** [comment]
It's a lot simpler here.  Just use conda-build 3.  Since the compiler packages that it uses are all self-contained with their own sysroots, it's just a matter of letting the compiler packages work their magic.

The only real trick to this is that you should issue build commands from the root of the aggregate folder, where conda_build_config.yaml lives, or manually specify an alternate conda_build_config.yaml file that conda-build should use.  That's the ``-m`` flag to conda-build.

we'll try to write up some docs soon, too.

**Comment by 183amir** [comment]
This is not working for me. For example take this recipe:
```yaml
{% set version = "1.0.0.1832.f7e6fca" %}

package:
  name: libblitz
  version: {{ version }}

source:
  git_url: https://github.com/wperkins/blitz.git
  git_rev: f7e6fca9ad683db7c0a41c250db346ccae6732c3

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libblitz') }}

requirements:
  build:
    - python 2
    - autoconf
    - automake
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - test -d $PREFIX/include/blitz        # [unix]
    - test -e $PREFIX/lib/libblitz.a       # [unix]
    - test -e $PREFIX/lib/libblitz.so      # [linux]
    - test -e $PREFIX/lib/libblitz.dylib   # [osx]

about:
  home: https://sourceforge.net/projects/blitz
  license: LGPL 3
  summary: A C++ class library for scientific computing which provides performance on par with Fortran 77/90
```
with this `build.sh`:
```sh
#!/bin/bash

if [[ $ARCH == 64 ]];
then
	export ARCH_CMD="--enable-64bit"
else
	export ARCH_CMD="--enable-simd-width=8"
fi

autoreconf -vif

./configure \
  --prefix="${PREFIX}" \
  --enable-static \
  --enable-shared \
  --enable-optimize \
  --enable-threadsafe \
  --enable-serialization \
  ${ARCH_CMD} \
  CPPFLAGS="-I${PREFIX}/include -pthread" \
  CFLAGS="-I${PREFIX}/include -pthread -DBZHAVE_STD" \
  CXXFLAGS="-I${PREFIX}/include -pthread -DBZHAVE_STD" \
  LDFLAGS="-L${PREFIX}/lib"
make
make check
make install
```
This recipe compiles fine on the `conda-concourse-ci` docker image but on my laptop which has Arch Linux it fails with the following error:
```
libtool: compile:  /home/amir/miniconda/conda-bld/libblitz_1507017058039/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/x86_64-conda_cos6-linux-gnu-c++ -DHAVE_CONFIG_H -I.. -I.. -I/usr/include -I/home/amir/miniconda/conda-bld/libblitz_1507017058039/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/include -pthread -O3 -funroll-loops -fstrict-aliasing -fomit-frame-pointer -ffast-math -DUSE_LIBBLAS -MT globals.lo -MD -MP -MF .deps/globals.Tpo -c ../src/globals.cpp  -fPIC -DPIC -o .libs/globals.o
In file included from /home/amir/miniconda/conda-bld/libblitz_1507017058039/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/x86_64-conda_cos6-linux-gnu/sysroot/usr/include/math.h:47:0,
                 from /home/amir/miniconda/conda-bld/libblitz_1507017058039/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/x86_64-conda_cos6-linux-gnu/include/c++/7.2.0/cmath:45,
                 from ../blitz/blitz.h:65,
                 from ../src/globals.cpp:11:
/usr/include/bits/mathdef.h:19:3: error: #error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
 # error "Never use <bits/mathdef.h> directly; include <complex.h> instead"
   ^~~~~
```
